apiVersion: v2
name: frontman-gateway
version: 1.0.0
description: A Helm chart for deploying the Frontman API Gateway
type: application
appVersion: 1.0.0
maintainers:
  - name: Simon Chapman
    email: simonchapman1986@gmail.com
