gateway:
  image: hyperioxx/frontman:v0.0.24
  serviceType: mongo
  mongoUrl: mongodb://<credetials>@<host and port>/frontman?authSource=admin
  apiAddr: 0.0.0.0:8081
  gatewayAddr: 0.0.0.0:8001
  apiSslEnabled: false
  apiSslCertPath: /certs/server.crt
  apiSslKeyPath: /certs/server.key
  gatewaySslEnabled: false
  gatewaySslCertPath: /certs/server.crt
  gatewaySslKeyPath: /certs/server.key
domain:
  api: localhost
tls:
  enabled: false
ingress:
  enabled: true
