apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: frontman
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: frontman-gateway
    app.kubernetes.io/part-of: frontman-gateway
spec:
  controller: ingress.k8s.frontman/controller

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontman-gateway-ingress
  annotations:
    kubernetes.io/ingress.class: frontman
spec:
  rules:
    - host: {{ .Values.domain.api }}
      http:
        paths:
          - path: /api/*
            pathType: Prefix
            backend:
              service:
                name: frontman-gateway
                port:
                  name: api
    - http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: frontman-gateway
                port:
                  name: gateway
  {{- if .Values.tls.enabled -}}
  tls:
    - hosts:
        - {{ .Values.domain.api }}
      secretName: tls-secret
  {{- end }}
