apiVersion: v1
kind: Service
metadata:
  name: frontman-gateway
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: frontman-gateway
    app.kubernetes.io/part-of: frontman-gateway
spec:
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: frontman-gateway
    app.kubernetes.io/part-of: frontman-gateway
  externalTrafficPolicy: Local
  ipFamilyPolicy: SingleStack
  ports:
    - appProtocol: http
      name: gateway
      port: 80
      protocol: TCP
      targetPort: 8001
    - appProtocol: http
      name: api
      port: 8081
      protocol: TCP
      targetPort: 8081
    - appProtocol: https
      name: https
      port: 443
      protocol: TCP
      targetPort: https
  type: LoadBalancer
