apiVersion: v1
kind: Service
metadata:
  name: frontman-gateway
spec:
  selector:
    app: frontman-gateway
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: gateway
      port: 8000
      targetPort: 8000
  type: LoadBalancer
